---
title: ויזואליזציה של משפט הגבול המרכזי
author: ophir betser
date: '2021-10-02'
slug: clt
categories: []
tags: []
subtitle: 'יצירת אפליקציות אינטרקטיביות עם הספריה shiny'
summary: 'יצירת אפליקציות אינטרקטיביות עם הספריה shiny'
authors: []
lastmod: '2021-10-02T04:24:03+03:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

<html dir="rtl">

שלום לכול מי שקורא את הפוסט :)

אני רוצה לספר למי שלא מכיר על הספריה
shiny.

shiny
היא ספריה
שמאפשרת לבנות אפליקציות אינטרקטיביות
דרך
R
.

שימוש בכלים אינטרקטיבים כחלק מהצגת העבודה שלנו עם נתונים יכול ממש לשדרג את העניין בניתוח הנתונים שלנו ובהבנה של המשמעות שלו.

הצגה של תוצאות הניתוח, תוך בניית סיפור מעניין והגיוני היא חלק מאוד חשוב בעבודה של מדען נתונים או אנליסט. האם עץ שנופל באמצע אי מבודד אכן משמיע רעש? האם גרף שאתה היחיד בעולם שראה אכן סורטט?

בשל העניין הזה שליטה בכליי ויזאליזיה, סטורי-טליג ובניית אפליקציות יכולה לחזק מאוד הרושם שהעבודה שלכם ישאיר על הצופים בו.

שימוש נוסף בכלים האלה יכול להיות עזר כאשר נושא חדש נלמד.

אני מצרף קישור לפוסט הזה לדוגמא ממש כזאת, שבה בניתי אפליציה פשוטה אשר מדגימה את תוצאות משפט הגבול המרכזי.

המסקנה של המשפט היא שממוצעים התפלגויות מתוך מרחב דגימה כלשהוא (הכלליות היא הכוח של המשפט)
מתפלגים באופן גבולי נורמלית.

כלומר, אם אני אגריל 
n
הגרלות שונות
בנות
m
תפציות מתוך התפלגות אחידה,
כל הגרלה בפני עצמה תתפלג באופן גבולי אחיד,
אך הממוצעים של ההגרלות יתפלגו באופן גבולי
(כש n שואף לאינסוף)
נורמלית.

מוזמנים לשחק באפליקציה, לקבל הרגשה של הבנה עמוקה יותר של מסקנות המשפט, כי אין כמו לראות דוגמא של תוצאות עבור הבנת נושאים מופשטים:


<div style="text-align:center;" dir="ltr">
[clt app](https://ophir-betser.shinyapps.io/clt_app/?_ga=2.74569106.1091192915.1632655554-1160489566.1631561296)
</div>

בהמשך אני אכתוב פוסט שבו אסביר על הקוד, ועל איך בונים אפליקציה בעזרת 
shiny.

אני חושב שאם עבור כל נושא קצת מסובך תהיה לסטודנטים גישה לכלים בסגנון הזה, חווית הלימודים תהיה יותר מהנה, וקצב הלימוד יוכל להיות יותר גבוה.

