---
title: "עברית בקובץ מארק-דאון"
output: html_document
---

<html dir="rtl">
    
    
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# load packages ----

options(scipen=999) # Disables scientific notation          
options(digits=6)   # Limits the number of digits printed       

Sys.setlocale(locale = "Hebrew")


if (!require("pacman")){                                  
    install.packages("pacman")}                            
pacman::p_load(pacman, data.table, DT, lubridate, dplyr, knitr, rmdformats,
               ggplot2, patchwork, visdat, esquisse, forcats, plotly, ggeasy,
               graphics, scico, cowplot, magick, stringi)
               
## Global options
options(max.print="75")
opts_chunk$set(#echo=FALSE,
    cache=TRUE,
    prompt=FALSE,
    tidy=TRUE,
    comment=NA,
    message=FALSE,
    warning=FALSE)
opts_knit$set(width=75)

```


## עברית

שלום לכולם וברוכים הבאים לבלוג שלי.

אני רוצה לוודא שככה אפשר לכתוב בעברית - בישור הטקסט מימין לשמאל.

בוא נעלה את הדף לאוויר!
  
  
  
מדהים, זה עובד!

  
ואפילו אפשר להציג קוד
R
בישור רגיל, בעזרת קסם של
html  

<div dir="ltr">
```{r pressure, echo=FALSE}
plot(pressure)
```
</div>



